<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.13">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Yirui Xu">
<meta name="dcterms.date" content="2026-05-25">

<title>MaxDiff Analysis of MSBA Class Preferences – Yirui Xu</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ac077c1e730dfeb5e42400639d17284e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-c5c0b1afe8f67f6d4c0aff8b5ee14551.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Yirui Xu</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../blog.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data">The Data</a></li>
  <li><a href="#counts-analysis" id="toc-counts-analysis" class="nav-link" data-scroll-target="#counts-analysis">Counts Analysis</a>
  <ul class="collapse">
  <li><a href="#counts-results" id="toc-counts-results" class="nav-link" data-scroll-target="#counts-results">Counts results</a></li>
  </ul></li>
  <li><a href="#from-maxdiff-data-to-mnl-choices" id="toc-from-maxdiff-data-to-mnl-choices" class="nav-link" data-scroll-target="#from-maxdiff-data-to-mnl-choices">From MaxDiff Data to MNL Choices</a></li>
  <li><a href="#mnl-via-maximum-likelihood" id="toc-mnl-via-maximum-likelihood" class="nav-link" data-scroll-target="#mnl-via-maximum-likelihood">MNL via Maximum Likelihood</a>
  <ul class="collapse">
  <li><a href="#mle-results" id="toc-mle-results" class="nav-link" data-scroll-target="#mle-results">MLE results</a></li>
  </ul></li>
  <li><a href="#mnl-via-bayesian-estimation" id="toc-mnl-via-bayesian-estimation" class="nav-link" data-scroll-target="#mnl-via-bayesian-estimation">MNL via Bayesian Estimation</a>
  <ul class="collapse">
  <li><a href="#bayesian-results" id="toc-bayesian-results" class="nav-link" data-scroll-target="#bayesian-results">Bayesian results</a></li>
  </ul></li>
  <li><a href="#comparing-the-three-methods" id="toc-comparing-the-three-methods" class="nav-link" data-scroll-target="#comparing-the-three-methods">Comparing the Three Methods</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">MaxDiff Analysis of MSBA Class Preferences</h1>
<p class="subtitle lead">Counts, maximum likelihood, and Bayesian estimation of the multinomial logit model</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Yirui Xu </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 25, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>MaxDiff, also called <em>Best-Worst Scaling</em>, is a survey method for measuring relative preference. Instead of asking respondents to assign each item a score on a numeric scale, MaxDiff repeatedly shows a small subset of items and asks them to choose the most preferred and least preferred option in that set. This design is attractive because people are usually much better at making trade-offs than at using a 1–10 scale consistently. A respondent may hesitate between giving an item a 7 or an 8, but they can usually tell which option they like most and which they like least in a set of four.</p>
<p>In this assignment, the ten items are the ten core MSBA classes at UCSD Rady. I estimate relative preference for these classes in three ways. First, I compute a simple <strong>counts analysis</strong> based on the percentage of times each class is picked as best minus the percentage of times it is picked as worst. Second, I estimate a <strong>multinomial logit (MNL)</strong> model by <strong>maximum likelihood</strong>. Third, I estimate the same MNL model in a <strong>Bayesian</strong> framework using a Metropolis-Hastings sampler. I expected these three methods to agree on the broad ranking of classes, especially at the top and bottom of the list, while allowing for some small differences in the middle where preferences are closer together.</p>
</section>
<section id="the-data" class="level2">
<h2 class="anchored" data-anchor-id="the-data">The Data</h2>
<p>The raw survey file contains one row per displayed item. The key variables are:</p>
<ul>
<li><code>Record ID</code>: anonymized respondent identifier</li>
<li><code>Task</code>: the screen number for that respondent</li>
<li><code>Position</code>: the slot on the screen</li>
<li><code>Item</code>: which course appears in that slot</li>
<li><code>Response</code>: <code>1</code> if the item was selected as best, <code>-1</code> if selected as worst, and <code>0</code> otherwise</li>
</ul>
<p>The item-label file maps each numeric item code to a course title.</p>
<p>The raw data contain <strong>85 respondents</strong>. A standard four-item MaxDiff task should contain exactly four rows, with one best choice, one worst choice, and two unchosen items. However, after checking the raw file carefully, I found that not all tasks followed this standard format. Some tasks contained four rows, while others contained only two. The raw data also included an extra item code beyond the ten labeled course items.</p>
<p>Because the multinomial logit model in this homework is built for standard four-item MaxDiff tasks, I restricted the analysis to tasks that satisfied three conditions:</p>
<ol type="1">
<li>exactly four displayed items,</li>
<li>exactly one best choice,</li>
<li>exactly one worst choice.</li>
</ol>
<p>After cleaning, the usable sample contained <strong>2,720 rows</strong>, corresponding to <strong>680 valid MaxDiff tasks</strong>. The final cleaned data included only the ten labeled MSBA classes. Exposure counts were also very balanced across items, which is what I would hope to see in a well-designed MaxDiff study.</p>
</section>
<section id="counts-analysis" class="level2">
<h2 class="anchored" data-anchor-id="counts-analysis">Counts Analysis</h2>
<p>I begin with the simplest descriptive approach. For each class <span class="math inline">\(begin:math:text\)</span>j<span class="math inline">\(end:math:text\)</span>, I calculate the share of times it was selected as best and the share of times it was selected as worst, conditional on being shown. I then define the counts score as</p>
<p><span class="math display">\[
\text{score}_j = \%\text{best}_j - \%\text{worst}_j.
\]</span></p>
<p>This score is easy to interpret. A large positive value means that a class is often chosen as best and rarely chosen as worst. A large negative value means the opposite.</p>
<section id="counts-results" class="level3">
<h3 class="anchored" data-anchor-id="counts-results">Counts results</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>Rank</th>
<th style="text-align: right;">Item</th>
<th>Class</th>
<th style="text-align: right;">Shown</th>
<th style="text-align: right;">Best</th>
<th style="text-align: right;">Worst</th>
<th style="text-align: right;">% Best</th>
<th style="text-align: right;">% Worst</th>
<th style="text-align: right;">Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td style="text-align: right;">9</td>
<td>MGTA 495 Marketing Analytics</td>
<td style="text-align: right;">274</td>
<td style="text-align: right;">147</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">0.5365</td>
<td style="text-align: right;">0.0438</td>
<td style="text-align: right;">0.4927</td>
</tr>
<tr class="even">
<td>2</td>
<td style="text-align: right;">5</td>
<td>MGTA 453 Business Analytics</td>
<td style="text-align: right;">270</td>
<td style="text-align: right;">93</td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">0.3444</td>
<td style="text-align: right;">0.2037</td>
<td style="text-align: right;">0.1407</td>
</tr>
<tr class="odd">
<td>3</td>
<td style="text-align: right;">7</td>
<td>MGTA 455 Customer Analytics</td>
<td style="text-align: right;">276</td>
<td style="text-align: right;">104</td>
<td style="text-align: right;">71</td>
<td style="text-align: right;">0.3768</td>
<td style="text-align: right;">0.2572</td>
<td style="text-align: right;">0.1196</td>
</tr>
<tr class="even">
<td>4</td>
<td style="text-align: right;">4</td>
<td>MGTA 452 Large Data</td>
<td style="text-align: right;">276</td>
<td style="text-align: right;">77</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">0.2790</td>
<td style="text-align: right;">0.2174</td>
<td style="text-align: right;">0.0616</td>
</tr>
<tr class="odd">
<td>5</td>
<td style="text-align: right;">8</td>
<td>MGTA 454 Capstone Project</td>
<td style="text-align: right;">272</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">69</td>
<td style="text-align: right;">0.2647</td>
<td style="text-align: right;">0.2537</td>
<td style="text-align: right;">0.0110</td>
</tr>
<tr class="even">
<td>6</td>
<td style="text-align: right;">2</td>
<td>MGTA 464 SQL</td>
<td style="text-align: right;">274</td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">0.2007</td>
<td style="text-align: right;">0.2044</td>
<td style="text-align: right;">-0.0036</td>
</tr>
<tr class="odd">
<td>7</td>
<td style="text-align: right;">10</td>
<td>MGTA 457 Biz. Intelligence Systems</td>
<td style="text-align: right;">266</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">0.0865</td>
<td style="text-align: right;">0.2068</td>
<td style="text-align: right;">-0.1203</td>
</tr>
<tr class="even">
<td>8</td>
<td style="text-align: right;">1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics</td>
<td style="text-align: right;">273</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">0.1209</td>
<td style="text-align: right;">0.3297</td>
<td style="text-align: right;">-0.2088</td>
</tr>
<tr class="odd">
<td>9</td>
<td style="text-align: right;">3</td>
<td>MGTA 451 Marketing/Finance/Operations</td>
<td style="text-align: right;">272</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">101</td>
<td style="text-align: right;">0.1581</td>
<td style="text-align: right;">0.3713</td>
<td style="text-align: right;">-0.2132</td>
</tr>
<tr class="even">
<td>10</td>
<td style="text-align: right;">6</td>
<td>MGTA 444 Analytics Consulting</td>
<td style="text-align: right;">267</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">111</td>
<td style="text-align: right;">0.1236</td>
<td style="text-align: right;">0.4157</td>
<td style="text-align: right;">-0.2921</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/counts_scores.png" class="img-fluid figure-img"></p>
<figcaption>Counts-Based MaxDiff Scores</figcaption>
</figure>
</div>
<p>The counts analysis already reveals a clear ranking. <strong>MGTA 495 Marketing Analytics</strong> is the dominant favorite by a large margin. <strong>MGTA 453 Business Analytics</strong> and <strong>MGTA 455 Customer Analytics</strong> also receive clearly positive scores, so they appear to be strong favorites as well. At the opposite end, <strong>MGTA 444 Analytics Consulting</strong> is the least attractive course in the counts analysis, followed by <strong>MGTA 451 Marketing/Finance/Operations</strong> and <strong>MGTA 403 AI Math, Programming, &amp; Analytics</strong>. Even before fitting a formal model, the preferences are far from uniform.</p>
</section>
</section>
<section id="from-maxdiff-data-to-mnl-choices" class="level2">
<h2 class="anchored" data-anchor-id="from-maxdiff-data-to-mnl-choices">From MaxDiff Data to MNL Choices</h2>
<p>To move beyond descriptive counts, I interpret the MaxDiff survey as a discrete-choice problem. On each screen, the respondent first chooses the <strong>best</strong> item from the four shown alternatives. Conditional on that best choice, the respondent then chooses the <strong>worst</strong> item from the remaining three.</p>
<p>If the set of shown items is <span class="math inline">\(begin:math:text\)</span>\{a,b,c,d\}<span class="math inline">\(end:math:text\)</span> and item <span class="math inline">\(begin:math:text\)</span>b<span class="math inline">\(end:math:text\)</span> is selected as best, the MNL probability of that choice is</p>
<p><span class="math display">\[
P(\text{best}=b)
=
\frac{\exp(\beta_b)}
{\exp(\beta_a)+\exp(\beta_b)+\exp(\beta_c)+\exp(\beta_d)}.
\]</span></p>
<p>If item <span class="math inline">\(begin:math:text\)</span>c<span class="math inline">\(end:math:text\)</span> is then chosen as worst from the remaining options, I model that worst choice by flipping the sign of utility:</p>
<p><span class="math display">\[
P(\text{worst}=c \mid \text{best}=b)
=
\frac{\exp(-\beta_c)}
{\sum_{j \in \{a,c,d\}} \exp(-\beta_j)}.
\]</span></p>
<p>This means that each MaxDiff task contributes <strong>two linked MNL observations</strong>: one for the best choice and one for the worst choice conditional on the best. Since the softmax is invariant to adding the same constant to every utility parameter, the model is not identified unless one coefficient is fixed. I therefore set one class as the baseline and interpret all remaining coefficients relative to it.</p>
<p>The value of this setup is that it models the choice process explicitly. Every shown item contributes information, not just the one selected as best or worst.</p>
</section>
<section id="mnl-via-maximum-likelihood" class="level2">
<h2 class="anchored" data-anchor-id="mnl-via-maximum-likelihood">MNL via Maximum Likelihood</h2>
<p>I first estimate the MNL model by maximum likelihood. For each task, the log-likelihood contribution is the log-probability of the observed best choice plus the log-probability of the observed worst choice conditional on the best choice. Summing across tasks gives</p>
<p><span class="math display">\[
\ell(\boldsymbol{\beta})
=
\sum_{\text{tasks}}
\left[
\beta_{j_b^*}
-
\log \sum_{j \in \text{shown}} \exp(\beta_j)
+
(-\beta_{j_w^*})
-
\log \sum_{j \in \text{shown} \setminus \{j_b^*\}} \exp(-\beta_j)
\right].
\]</span></p>
<p>The optimizer reported some precision loss, which suggests mild numerical instability in the Hessian approximation, but the estimated ranking itself is very stable and closely matches the descriptive evidence.</p>
<p>To make the MLE results easier to interpret, I convert the utility coefficients into <strong>shares of preference</strong>:</p>
<p><span class="math display">\[
\hat{s}_j
=
\frac{\exp(\hat{\beta}_j)}
{\sum_{k=1}^{10} \exp(\hat{\beta}_k)}.
\]</span></p>
<p>These shares answer the question: <em>if all ten classes were shown on a single screen, what fraction of choices would each class receive?</em></p>
<section id="mle-results" class="level3">
<h3 class="anchored" data-anchor-id="mle-results">MLE results</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 18%">
<col style="width: 13%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th>Rank</th>
<th style="text-align: right;">Item</th>
<th>Class</th>
<th style="text-align: right;"><span class="math inline">\(begin:math:text\)</span>\hat{\beta}<span class="math inline">\(end:math:text\)</span></th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">Share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td style="text-align: right;">9</td>
<td>MGTA 495 Marketing Analytics</td>
<td style="text-align: right;">1.6298</td>
<td style="text-align: right;">0.0901</td>
<td style="text-align: right;">0.2839</td>
</tr>
<tr class="even">
<td>2</td>
<td style="text-align: right;">5</td>
<td>MGTA 453 Business Analytics</td>
<td style="text-align: right;">0.7445</td>
<td style="text-align: right;">0.1137</td>
<td style="text-align: right;">0.1171</td>
</tr>
<tr class="odd">
<td>3</td>
<td style="text-align: right;">7</td>
<td>MGTA 455 Customer Analytics</td>
<td style="text-align: right;">0.6563</td>
<td style="text-align: right;">0.0852</td>
<td style="text-align: right;">0.1072</td>
</tr>
<tr class="even">
<td>4</td>
<td style="text-align: right;">4</td>
<td>MGTA 452 Large Data</td>
<td style="text-align: right;">0.5553</td>
<td style="text-align: right;">0.0701</td>
<td style="text-align: right;">0.0969</td>
</tr>
<tr class="odd">
<td>5</td>
<td style="text-align: right;">8</td>
<td>MGTA 454 Capstone Project</td>
<td style="text-align: right;">0.4433</td>
<td style="text-align: right;">0.0834</td>
<td style="text-align: right;">0.0867</td>
</tr>
<tr class="even">
<td>6</td>
<td style="text-align: right;">2</td>
<td>MGTA 464 SQL</td>
<td style="text-align: right;">0.4380</td>
<td style="text-align: right;">0.0513</td>
<td style="text-align: right;">0.0862</td>
</tr>
<tr class="odd">
<td>7</td>
<td style="text-align: right;">10</td>
<td>MGTA 457 Biz. Intelligence Systems</td>
<td style="text-align: right;">0.2359</td>
<td style="text-align: right;">0.1017</td>
<td style="text-align: right;">0.0704</td>
</tr>
<tr class="even">
<td>8</td>
<td style="text-align: right;">1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">0.0556</td>
</tr>
<tr class="odd">
<td>9</td>
<td style="text-align: right;">3</td>
<td>MGTA 451 Marketing/Finance/Operations</td>
<td style="text-align: right;">-0.0666</td>
<td style="text-align: right;">0.1075</td>
<td style="text-align: right;">0.0520</td>
</tr>
<tr class="even">
<td>10</td>
<td style="text-align: right;">6</td>
<td>MGTA 444 Analytics Consulting</td>
<td style="text-align: right;">-0.2388</td>
<td style="text-align: right;">0.1194</td>
<td style="text-align: right;">0.0438</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/mle_shares.png" class="img-fluid figure-img"></p>
<figcaption>MNL Shares of Preference (MLE)</figcaption>
</figure>
</div>
<p>The MLE results tell essentially the same story as the counts analysis. <strong>MGTA 495 Marketing Analytics</strong> remains the strongest course by a large margin. It is followed by <strong>MGTA 453 Business Analytics</strong>, <strong>MGTA 455 Customer Analytics</strong>, and <strong>MGTA 452 Large Data</strong>. At the bottom of the ranking, <strong>MGTA 444 Analytics Consulting</strong> again appears weakest. The main differences relative to the counts analysis occur in the middle of the ranking, where several classes have similar utility.</p>
</section>
</section>
<section id="mnl-via-bayesian-estimation" class="level2">
<h2 class="anchored" data-anchor-id="mnl-via-bayesian-estimation">MNL via Bayesian Estimation</h2>
<p>I next estimate the same MNL model in a Bayesian framework. Instead of treating the coefficients as fixed but unknown, the Bayesian approach treats them as random variables and combines the likelihood with a prior:</p>
<p><span class="math display">\[
\pi(\boldsymbol{\beta}\mid\mathbf{y})
\propto
L(\boldsymbol{\beta}) \cdot \pi(\boldsymbol{\beta}).
\]</span></p>
<p>I use a weakly informative Normal prior on the free coefficients:</p>
<p><span class="math display">\[
\beta_k \sim N(0, 10).
\]</span></p>
<p>I then approximate the posterior with a random-walk Metropolis-Hastings sampler. In the notebook implementation, the sampler used 2,000 draws with a burn-in of 500 and achieved an <strong>acceptance rate of 0.398</strong>, which is well within a reasonable range for this kind of algorithm. <a href="sediment://file_000000006df4720fb3d6e22e4e365a86">oai_citation:0‡hw4.pdf</a></p>
<section id="bayesian-results" class="level3">
<h3 class="anchored" data-anchor-id="bayesian-results">Bayesian results</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 16%">
<col style="width: 12%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 12%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Rank</th>
<th style="text-align: right;">Item</th>
<th>Class</th>
<th style="text-align: right;">Posterior Mean</th>
<th style="text-align: right;">Posterior SD</th>
<th>95% CI</th>
<th style="text-align: right;">Posterior Mean Share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td style="text-align: right;">9</td>
<td>MGTA 495 Marketing Analytics</td>
<td style="text-align: right;">1.6189</td>
<td style="text-align: right;">0.1225</td>
<td>[1.3780, 1.8365]</td>
<td style="text-align: right;">0.2828</td>
</tr>
<tr class="even">
<td>2</td>
<td style="text-align: right;">5</td>
<td>MGTA 453 Business Analytics</td>
<td style="text-align: right;">0.7279</td>
<td style="text-align: right;">0.1657</td>
<td>[0.3936, 1.0157]</td>
<td style="text-align: right;">0.1163</td>
</tr>
<tr class="odd">
<td>3</td>
<td style="text-align: right;">7</td>
<td>MGTA 455 Customer Analytics</td>
<td style="text-align: right;">0.6565</td>
<td style="text-align: right;">0.1284</td>
<td>[0.3888, 0.8794]</td>
<td style="text-align: right;">0.1083</td>
</tr>
<tr class="even">
<td>4</td>
<td style="text-align: right;">4</td>
<td>MGTA 452 Large Data</td>
<td style="text-align: right;">0.5525</td>
<td style="text-align: right;">0.1630</td>
<td>[0.2757, 0.8703]</td>
<td style="text-align: right;">0.0976</td>
</tr>
<tr class="odd">
<td>5</td>
<td style="text-align: right;">2</td>
<td>MGTA 464 SQL</td>
<td style="text-align: right;">0.4208</td>
<td style="text-align: right;">0.1362</td>
<td>[0.1733, 0.7176]</td>
<td style="text-align: right;">0.0855</td>
</tr>
<tr class="even">
<td>6</td>
<td style="text-align: right;">8</td>
<td>MGTA 454 Capstone Project</td>
<td style="text-align: right;">0.4164</td>
<td style="text-align: right;">0.1340</td>
<td>[0.1437, 0.6695]</td>
<td style="text-align: right;">0.0851</td>
</tr>
<tr class="odd">
<td>7</td>
<td style="text-align: right;">10</td>
<td>MGTA 457 Biz. Intelligence Systems</td>
<td style="text-align: right;">0.2462</td>
<td style="text-align: right;">0.1428</td>
<td>[-0.0385, 0.5174]</td>
<td style="text-align: right;">0.0718</td>
</tr>
<tr class="even">
<td>8</td>
<td style="text-align: right;">1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">—</td>
<td>—</td>
<td style="text-align: right;">0.0562</td>
</tr>
<tr class="odd">
<td>9</td>
<td style="text-align: right;">3</td>
<td>MGTA 451 Marketing/Finance/Operations</td>
<td style="text-align: right;">-0.0670</td>
<td style="text-align: right;">0.1504</td>
<td>[-0.4632, 0.1895]</td>
<td style="text-align: right;">0.0526</td>
</tr>
<tr class="even">
<td>10</td>
<td style="text-align: right;">6</td>
<td>MGTA 444 Analytics Consulting</td>
<td style="text-align: right;">-0.2480</td>
<td style="text-align: right;">0.1466</td>
<td>[-0.5313, 0.0288]</td>
<td style="text-align: right;">0.0438</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/trace_item9.png" class="img-fluid figure-img"></p>
<figcaption>Trace Plot for Item 9</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/bayes_shares.png" class="img-fluid figure-img"></p>
<figcaption>Bayesian MNL Shares of Preference</figcaption>
</figure>
</div>
<p>The Bayesian estimates are very close to the MLE estimates. <strong>MGTA 495</strong> remains the most preferred class, while <strong>MGTA 444</strong> remains the least preferred. The posterior means are slightly shrunk toward zero relative to the MLE estimates, which is exactly what I would expect under a weakly informative prior. The trace plot for item 9 also looks reasonably stable for the purposes of this homework.</p>
</section>
</section>
<section id="comparing-the-three-methods" class="level2">
<h2 class="anchored" data-anchor-id="comparing-the-three-methods">Comparing the Three Methods</h2>
<p>The table below summarizes the ranking under all three approaches.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 9%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Item</th>
<th>Class</th>
<th style="text-align: right;">Counts Score</th>
<th style="text-align: right;">Counts Rank</th>
<th style="text-align: right;">MLE Share</th>
<th style="text-align: right;">MLE Rank</th>
<th style="text-align: right;">Bayes Share</th>
<th style="text-align: right;">Bayes Rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">9</td>
<td>MGTA 495 Marketing Analytics</td>
<td style="text-align: right;">0.4927</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.2839</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.2828</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td>MGTA 453 Business Analytics</td>
<td style="text-align: right;">0.1407</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.1171</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.1163</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td>MGTA 455 Customer Analytics</td>
<td style="text-align: right;">0.1196</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.1072</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.1083</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td>MGTA 452 Large Data</td>
<td style="text-align: right;">0.0616</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.0969</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.0976</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: right;">8</td>
<td>MGTA 454 Capstone Project</td>
<td style="text-align: right;">0.0110</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.0867</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.0851</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td>MGTA 464 SQL</td>
<td style="text-align: right;">-0.0036</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.0862</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.0855</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="odd">
<td style="text-align: right;">10</td>
<td>MGTA 457 Biz. Intelligence Systems</td>
<td style="text-align: right;">-0.1203</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.0704</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.0718</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics</td>
<td style="text-align: right;">-0.2088</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.0556</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.0562</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td>MGTA 451 Marketing/Finance/Operations</td>
<td style="text-align: right;">-0.2132</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0.0520</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0.0526</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td>MGTA 444 Analytics Consulting</td>
<td style="text-align: right;">-0.2921</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0.0438</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0.0438</td>
<td style="text-align: right;">10</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/compare_methods.png" class="img-fluid figure-img"></p>
<figcaption>Comparison of Counts, MLE, and Bayesian Methods</figcaption>
</figure>
</div>
<p>The three methods agree strongly on the broad structure of preferences. All three identify <strong>MGTA 495 Marketing Analytics</strong> as the top-ranked class. They also consistently place <strong>MGTA 444 Analytics Consulting</strong> and <strong>MGTA 457 Business Intelligence Systems</strong> near the bottom. The main disagreement occurs in the middle of the ranking: <strong>MGTA 454 Capstone Project</strong> and <strong>MGTA 464 SQL</strong> switch positions between MLE and Bayes, which is exactly the sort of small movement I would expect when items are close together.</p>
<p>The counts approach is useful as a quick descriptive summary. The MNL model adds a formal utility-based interpretation and uses the full choice structure more explicitly. The Bayesian version adds a natural way to quantify uncertainty for derived quantities like preference shares. In this application, however, the Bayesian and MLE estimates are so similar that the core substantive conclusions are very stable.</p>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<p>The clearest substantive finding is that students in this sample strongly prefer <strong>MGTA 495 Marketing Analytics</strong>, with <strong>MGTA 453 Business Analytics</strong> and <strong>MGTA 455 Customer Analytics</strong> also standing out as highly attractive classes. This pattern is intuitive. These courses are closely tied to applied analytics skills and practical business uses, which likely makes them especially appealing to students in an MSBA program.</p>
<p>At the lower end of the ranking, <strong>MGTA 444 Analytics Consulting</strong> appears least attractive, followed by <strong>MGTA 451 Marketing/Finance/Operations</strong> and <strong>MGTA 403 AI Math, Programming, &amp; Analytics</strong>. That does not necessarily mean that these courses are unimportant. Rather, it means that in repeated forced-choice comparisons, students were less likely to choose them as the most preferred option relative to the rest of the core curriculum.</p>
<p>Methodologically, the assignment shows why it is useful to examine the same preference data from multiple angles. A <strong>counts analysis</strong> is fast, intuitive, and useful for a dashboard-style summary. An <strong>MLE MNL</strong> model is more rigorous when the goal is to estimate a coherent latent utility structure and report a single set of point estimates. A <strong>Bayesian MNL</strong> model is especially useful when uncertainty matters for derived quantities such as preference shares or when one wants to extend the model later to allow for respondent-level heterogeneity.</p>
<p>There are also important caveats. The survey reflects a self-selected sample of MSBA students, so the results should not be interpreted as universal preferences for all students or future cohorts. Preferences may depend on prior coursework, specialization interests, and where a student currently is in the program. If I had more time, the next step would be to estimate a hierarchical model that allows preferences to vary across individuals rather than assuming a single common utility vector for all respondents.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>